.PHONY:all_out first second third test

all_out:
	@echo "$(MAKE)"
	@echo "$(MAKECMDGOALS)"
	@echo "$(MAKEFILE_LIST)"
first:
	@echo "first"
second:
	@echo "second"
third:
	@echo "third"
test:
	@$(MAKE) first
	@$(MAKE) second
	@$(MAKE) third

