CC:=g++
TARGET:=hello-world.out

$(TARGET):func.o main.o
	$(CC) -o $@ $^
func.o:func.c
	$(CC) -o $@ -c $^
main.o:main.c
	$(CC) -o $@ -c $^
.PHONY:rebuild clean all

all:$(TARGET)
clean:
	$(RM) *.o $(TARGET)
