CC:=g++
TARGET:=hello-world.out
OBJS := func.o main.o const.o

$(TARGET):$(OBJS)
	$(CC) -o $@ $^
$(OBJS):%.o:%.c
	$(CC) -o $@ -c $^
.PHONY:rebuild clean all

all:$(TARGET)
clean:
	$(RM) *.o $(TARGET)
